apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # 任意の PVC 名
  name: nfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-server
