kind: Deployment
apiVersion: apps/v1
metadata:
  name: api-deployment-v35
spec:
  selector:
    matchLabels:
      server: api
  replicas: 3
  template:
    metadata:
      labels:
        server: api
    spec:
      initContainers:
        - name: seed
          image: tomo0726/keyaki2023-production-seed:latest
      containers:
        - name: api
          image: tomo0726/keyaki2023-production-api:latest
          resources:
            requests:
              cpu: 900m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 600Mi
          ports:
            - containerPort: 80
