kind: Deployment
apiVersion: apps/v1
metadata:
  name: api-deployment-v37
spec:
  selector:
    matchLabels:
      server: api
  replicas: 2
  template:
    metadata:
      labels:
        server: api
    spec:
      initContainers:
        - name: seed
          image: tomo0726/keyaki2023-production-seed:latest
      containers:
        - name: api
          image: tomo0726/keyaki2023-production-api:latest
          resources:
            requests:
              cpu: 25m
              memory: 50Mi
            limits:
              cpu: 50m
              memory: 100Mi
          ports:
            - containerPort: 80
