kind: Deployment
apiVersion: apps/v1
metadata:
  name: api-deployment-v2
spec:
  selector:
    matchLabels:
      server: api
  replicas: 3
  template:
    metadata:
      labels:
        server: api
    spec:
      containers:
        - name: api
          image: tomo0726/keyaki2023-production-api:latest
          resources:
            requests:
              cpu: 500m
              memory: 128Mi
            limits:
              cpu: 2000m
              memory: 256Mi
          ports:
            - containerPort: 80
