kind: Deployment
apiVersion: apps/v1
metadata:
  name: app-deployment-v10
spec:
  selector:
    matchLabels:
      server: app
  replicas: 3
  template:
    metadata:
      labels:
        server: app
    spec:
      containers:
        - name: app
          image: tomo0726/keyaki2023-production-app:latest
          resources:
            requests:
              cpu: 250m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 128Mi
          ports:
            - containerPort: 80
