kind: Deployment
apiVersion: apps/v1
metadata:
  name: app-deployment-v40
spec:
  selector:
    matchLabels:
      server: app
  replicas: 3
  template:
    metadata:
      labels:
        server: app
    spec:
      containers:
        - name: app
          image: tomo0726/keyaki2023-production-app:latest
          resources:
            requests:
              cpu: 300m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 512Mi
          ports:
            - containerPort: 80
