apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keyaki2023-ingress
  annotations:
    cert-manager.io/cluster-issuer: lets-encrypt
spec:
  tls:
    - hosts:
        - hiroogakuen.net
      secretName: microbot-ingress-tls
  rules:
    - host: hiroogakuen.net
      http:
        paths:
          - backend:
              service:
                name: nginx-service
                port:
                  number: 80
            path: /
            pathType: Prefix
