apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-deployment-v12
  minReplicas: 3
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        # CPU 使用率が 20% を超えたらスケーリング
        name: cpu
        target:
          type: Utilization
          averageUtilization: 40
