kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx-deployment-v36
spec:
  selector:
    matchLabels:
      server: nginx
  replicas: 4
  template:
    metadata:
      labels:
        server: nginx
    spec:
      containers:
        - name: nginx
          image: tomo0726/keyaki2023-production-nginx:latest
          resources:
            requests:
              cpu: 250m
              memory: 64Mi
            limits:
              cpu: 1000m
              memory: 512Mi
          ports:
            - containerPort: 80
