kind: Deployment
apiVersion: apps/v1
metadata:
  name: api-deployment-v25
spec:
  selector:
    matchLabels:
      server: api
  replicas: 1
  template:
    metadata:
      labels:
        server: api
    spec:
      containers:
        - name: api
          image: tomo0726/keyaki2023-test-api:latest
          ports:
            - containerPort: 80
          resources:
          # requests : pod 作成時に必要とするリソースを設定
          requests:
            # 250m : 0.25 CPU
            cpu: 250m
            memory: 64Mi
          # 使用可能なリソースの上限を設定
          limits:
            cpu: 500m
            memory: 128Mi
