kind: Deployment
apiVersion: apps/v1
metadata:
  name: api-deployment
spec:
  selector:
    matchLabels:
      server: api
  replicas: 3
  template:
    metadata:
      labels:
        server: api
    spec:
      containers:
        - name: api
          image: tomo0726/keyaki2023-test-api:latest
          ports:
            - containerPort: 80
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
