apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-deployment-v25
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        # CPU 使用率が 20% を超えたらスケーリング
        name: cpu
        target:
          type: Utilization
          averageUtilization: 20
