kind: Deployment
apiVersion: apps/v1
metadata:
  name: api-deployment-v25
spec:
  selector:
    matchLabels:
      server: api
  replicas: 1
  template:
    metadata:
      labels:
        server: api
    spec:
      containers:
        - name: api
          image: tomo0726/keyaki2023-test-api:latest
          resources:
            requests:
              cpu: 250m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 128Mi
          ports:
            - containerPort: 80
