kind: Deployment
apiVersion: apps/v1
metadata:
  name: api-deployment-v25
spec:
  selector:
    matchLabels:
      server: api
  minReplicas: 3
  # レプリカの最大数
  maxReplicas: 20
  metrics:
    - type: Resource
      resource:
        # CPU 使用率が 20% を超えたらスケーリング
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
  template:
    metadata:
      labels:
        server: api
    spec:
      containers:
        - name: api
          image: tomo0726/keyaki2023-test-api:latest
          ports:
            - containerPort: 80
