kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx-deployment-v18
spec:
  selector:
    matchLabels:
      server: nginx
  replicas: 3
  template:
    metadata:
      labels:
        server: nginx
    spec:
      containers:
        - name: nginx
          image: tomo0726/keyaki2023-test-nginx:latest
          ports:
            - containerPort: 80
