kind: Deployment
apiVersion: apps/v1
metadata:
  name: ubuntu-deployment
spec:
  selector:
    matchLabels:
      server: ubuntu
  replicas: 1
  template:
    metadata:
      labels:
        server: ubuntu
    spec:
      containers:
        - name: ubuntu
          image: ubuntu
          ports:
            - containerPort: 80
            - containerPort: 3306
